# Generated by Django 3.2 on 2021-05-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='本文')),
            ],
            options={
                'verbose_name_plural': 'スキルの概要',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('imgURL', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像のURL')),
                ('career', models.CharField(blank=True, max_length=55, null=True, verbose_name='職業')),
                ('age', models.CharField(blank=True, max_length=55, null=True, verbose_name='年齢')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GithubのURL')),
                ('introduction', models.TextField(verbose_name='自己紹介文')),
            ],
            options={
                'verbose_name_plural': 'プロフィール',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('imgURL', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像のURL')),
                ('url', models.URLField(verbose_name='URL')),
                ('published', models.DateField(blank=True, null=True, verbose_name='公開日')),
            ],
            options={
                'verbose_name_plural': '作品',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('years', models.FloatField(default=0, verbose_name='経験年数')),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.description', verbose_name='概要')),
            ],
            options={
                'verbose_name_plural': 'スキル',
            },
        ),
    ]
